version: "2"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  postgres:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=John
      - POSTGRES_PASSWORD=SecretPassw0rd
      - POSTGRES_DB=example
    volumes:
      - /srv/docker/postgresql-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
