# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsQuery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created date'),
        ),
    ]
